; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]  ; [env:xxx] 定义一个“编译环境”
platform = espressif32  ; 这个平台支持 ESP32、ESP32-C3、ESP32-S3 等芯片
board = esp32-c3-devkitm-1  ; 这个选项会影响芯片型号、Flash 默认大小、引脚定义等
framework = espidf  ; 使用 ESP-IDF 框架进行开发
monitor_speed = 115200  ; ESP-IDF 默认日志波特率通常也是 115200
board_build.flash_size = 2MB  ; 告诉编译系统：这块板子的 Flash 大小按 2MB 处理
upload_port = COM5  ; 烧录程序
monitor_port = COM5  ; 查看日志